# file: postgresql/tasks/users_privileges.yml

- name: PostgreSQL | Update the user privileges
  postgresql_privs:
    roles: "{{ item.roles }}"
    database: "{{ item.database | default(omit) }}"
    port: "{{ postgresql_port}}"
    privs: "{{ item.privs | mandatory }}"
    type: "{{ item.type | default(omit) }}"
    objs: "{{ item.objs | default(omit) }}"
    schema: "{{ item.schema | default(omit) }}"
    grant_option: "{{ item.grant_option | default(omit) }}"
    state: present
    login_host: "{{ item.host | default(omit) }}"
    login_user: "{{ postgresql_admin_user }}"
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  with_items: "{{ postgresql_user_privileges | default([]) }}"
